version: 2.1

workflows:
  sonarcloud-vars:
    jobs:
      - build:
          context: sonarcloud_env

orbs:
    android: circleci/android@1.0.3

jobs:
  build:
    working_directory: ~/code

    executor:
      name: android/android-machine
      resource-class: large

      steps:
      - checkout
      - android/restore-build-cache
      - android/restore-gradle-cache

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - android/save-build-cache
      - android/save-gradle-cache

      - android/run-tests:
          name: unit test on sonarqube
          command: ./gradlew sonarqube

      - store_artifacts:
          path: build/reports/jacoco/jacocoRootReportDebug/jacocoRootReportDebug.xml

      - run:
          name: clean previous build
          command: ./gradlew clean

      - run:
          name: ui test on browserstack
          command: ./gradlew executeDebugTestsOnBrowserstack

      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk

          # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
