version: 2.1

workflows:
  sonarcloud-vars:
    jobs:
      - build:
          context: sonarcloud_env

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: unit test on sonarqube
          command: ./gradlew sonarqube

      - store_artifacts:
          path: build/reports/jacoco/jacocoRootReportDebug/jacocoRootReportDebug.xml

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit         

      - run:
          name: clean previous build
          command: ./gradlew clean

      - run:
          name: ui test on browserstack
          command: ./gradlew executeDebugTestsOnBrowserstack

      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk

          # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
