version: 2.1

workflows:
  sonarcloud-vars:
    jobs:
      - build:
          context: sonarcloud_env # needed for ./gradlew sonarqube run smoothly

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      #      - run:
      #         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
      #         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: unit test on sonarqube
          command: ./gradlew sonarqube

      - run:
          name: clean previous build
          command: ./gradlew clean

      - run:
          name: ui test on browserstack
          command: ./gradlew sonarqube


      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples